---
title: "Human Day Data Processing"
output: html_document
date: "2024-03-24"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

NOTE: Almost all of this code is from Jonathan Kitt's preprocessing done for his visualization. You will find the original here: https://jonathankitt.netlify.app/posts/2023-09-12-tt-global-human-day/

## Data Import

```{r}
all_countries <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-09-12/all_countries.csv")
global_human_day <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-09-12/global_human_day.csv")
```


## Cleaning the data - from Jonathan Kitt 

```{r}
library(tidyverse)

categories <- all_countries |>
  # extract unique values
  distinct(Category, Subcategory)

d <- global_human_day |>
  # join the categories
  left_join(categories) |>
  # select columns
  select(Category, hoursPerDay) |>
  # add hours per category
  summarise(total = sum(hoursPerDay), .by = Category) |>
  # arrange by decreasing amount of time
  arrange(-total) |>
  # split the total column into two values
  separate(col = total, into = c("h", "m"), remove = F) |>
  # transform the trailing hours value into minutes
  mutate(m = round(as.numeric(paste0("0.", m)) * 60),
         h = as.numeric(h)) |>
  # create labels for plots
  mutate(duration = case_when(h == 0 ~ paste0(m, "m"),
                              TRUE ~ paste0(h, "h ", m, "m"))) |>
  # select columns
  select(Category, total, duration)
```


## Data by Country
```{r}
length(table(all_countries$country_iso3))
```



## Exporting the data

```{r}
write.csv(d, "global_human_day_cleaned.csv")
write.csv(categories, "global_human_day_categories.csv")
```



